kind: pipeline
type: docker
name: build

steps:
- name: build-angular
  image: circleci/node:14.18.2-buster
  user: root
  commands:
    - cd angular-app/
    - npm install
    - npm run build --configuration=production

- name: build-golang
  image: circleci/golang:1.17-buster-browsers-legacy
  user: root
  commands:
    - go test ./...
    - go build -o bin/templater
