kind: pipeline
type: docker
name: build

steps:
- name: test-angular
  image: matseee/golang-node:go1.19.0-node18.7.0-alpine3.16
  commands:
    - cd angular-app/
    - npm install
    - npm run test-headless

- name: test-golang
  image: matseee/golang-node:go1.19.0-node18.7.0-alpine3.16
  commands:
    - go test -v ./...

- name: build-angular
  image: matseee/golang-node:go1.19.0-node18.7.0-alpine3.16
  depends_on:
    - test-golang
    - test-angular
  commands:
    - npm run build --configuration=production

- name: build-golang
  image: matseee/golang-node:go1.19.0-node18.7.0-alpine3.16
  depends_on:
    - build-angular
  commands:
    - go build -o bin/templater
